@echo off
cls
echo.
echo ============================================================
echo   SOLUSI FINAL - FIX LOGIN DEMO MODE
echo   Script ini akan MEMASTIKAN demo mode aktif 100%%
echo ============================================================
echo.
echo Langkah yang akan dilakukan:
echo   1. Backup semua file .env
echo   2. Buat file .env baru yang PASTI benar
echo   3. Hapus folder dist lama
echo   4. Build dengan verifikasi
echo   5. Cek hasil build
echo.
pause
echo.

REM ============================================================
REM STEP 1: BACKUP
REM ============================================================
echo [STEP 1/5] Backup file .env...
if exist .env (
    copy /Y .env .env.backup.%date:~-4,4%%date:~-10,2%%date:~-7,2%_%time:~0,2%%time:~3,2%%time:~6,2%
    echo OK - Backup tersimpan
) else (
    echo WARNING - File .env tidak ada
)
echo.

REM ============================================================
REM STEP 2: BUAT FILE .ENV BARU YANG PASTI BENAR
REM ============================================================
echo [STEP 2/5] Membuat file .env baru...
echo # DEMO MODE - AUTO GENERATED BY FINAL FIX SCRIPT > .env
echo # Generated: %date% %time% >> .env
echo VITE_DEMO_AUTH=true >> .env
echo.
echo File .env berisi:
type .env
echo.
echo OK - File .env dibuat
echo.

REM ============================================================
REM STEP 3: HAPUS DIST LAMA
REM ============================================================
echo [STEP 3/5] Menghapus folder dist lama...
if exist dist (
    rmdir /s /q dist
    echo OK - Folder dist dihapus
) else (
    echo OK - Folder dist tidak ada
)
echo.

REM ============================================================
REM STEP 4: BUILD
REM ============================================================
echo [STEP 4/5] Building dengan demo mode...
echo ============================================================
echo.
call npm run build
echo.
echo ============================================================
echo.

REM ============================================================
REM STEP 5: VERIFIKASI
REM ============================================================
echo [STEP 5/5] Verifikasi hasil build...
echo.
if exist dist\index.html (
    echo [OK] File dist\index.html ditemukan
) else (
    echo [ERROR] File dist\index.html TIDAK ditemukan!
    goto :error
)

if exist dist\assets (
    echo [OK] Folder dist\assets ditemukan
) else (
    echo [ERROR] Folder dist\assets TIDAK ditemukan!
    goto :error
)

echo.
echo ============================================================
echo   BUILD BERHASIL - VERIFIKASI SUKSES!
echo ============================================================
echo.
echo FILE .env FINAL:
type .env
echo.
echo.
echo FOLDER dist SIAP DI-UPLOAD:
dir dist /b
echo.
echo.
echo ============================================================
echo   DEMO ACCOUNTS UNTUK LOGIN:
echo ============================================================
echo.
echo   1. OPERATOR DESA (Admin Lengkap)
echo      Phone: 08123456789
echo      Password: operator123
echo      Dashboard: /dashboard/operator
echo.
echo   2. KEPALA DUSUN (Manajemen RT/RW)
echo      Phone: 081234560000
echo      Password: dusun123
echo      Dashboard: /dashboard/dusun
echo.
echo   3. WARGA (Layanan Masyarakat)
echo      Phone: 081234560011
echo      Password: pengguna123
echo      Dashboard: /dashboard/citizen
echo.
echo ============================================================
echo   CARA UPLOAD KE HOSTING:
echo ============================================================
echo.
echo   1. Buka folder 'dist' di File Explorer
echo   2. Select ALL files dan folders di dalam 'dist'
echo   3. Upload ke hosting (public_html atau www)
echo   4. Overwrite semua file yang ada
echo   5. Buka browser ke: https://desafajarbaru.co/login
echo   6. WAJIB hard refresh: Ctrl + Shift + R
echo.
echo ============================================================
echo   VERIFIKASI SETELAH UPLOAD:
echo ============================================================
echo.
echo   Yang HARUS MUNCUL di halaman login:
echo   [✓] Banner "Mode Demo Aktif" (warna biru-hijau)
echo   [✓] Section "Akun Demo - Tanpa Backend"
echo   [✓] List 3 demo accounts dengan button "Gunakan"
echo.
echo   Console browser (F12) HARUS menunjukkan:
echo   [✓] "🎭 DEMO MODE AKTIF"
echo   [✓] "✅ Login tersedia tanpa backend"
echo.
echo   Jika TIDAK muncul = ulangi upload atau hubungi saya
echo.
echo ============================================================
echo.
goto :end

:error
echo.
echo ============================================================
echo   ERROR - BUILD GAGAL!
echo ============================================================
echo.
echo   Kemungkinan masalah:
echo   - npm dependencies belum terinstall
echo   - Error di kode TypeScript
echo   - Disk space penuh
echo.
echo   Solusi:
echo   1. Jalankan: npm install
echo   2. Jalankan script ini lagi
echo.
goto :end

:end
pause
