-- 002_seed_sample.sql
-- Optional sample data to verify endpoints. Edit as needed before running.
SET NAMES utf8mb4;

-- NOTE: Replace PASSWORD HASH below with a real bcrypt hash generated by your backend (PHP).
-- Example to generate in PHP: password_hash('yourStrongPassword', PASSWORD_BCRYPT)

-- Create an operator user (EDIT BEFORE RUN)
INSERT INTO users (username, email, phone, password_hash, full_name, role, status)
VALUES ('operator', 'operator@desafajarbaru.id', '081200000000', 'REPLACE_WITH_BCRYPT_HASH', 'Operator Desa', 'operator', 'active');

-- Transparency examples
INSERT INTO transparency_data (type, title, description, year, quarter, status)
VALUES 
('apb', 'APBDes 2024', 'Anggaran Pendapatan dan Belanja Desa 2024', 2024, 4, 'active'),
('idm', 'Indeks Desa Membangun 2024', 'Nilai IDM tahun berjalan', 2024, NULL, 'active');

-- Programs examples
INSERT INTO village_programs (name, type, description, beneficiaries, budget, status)
VALUES
('BUMDes Fajar Sejahtera', 'ekonomi', 'Pemberdayaan ekonomi desa melalui BUMDes', 120, 850000000, 'active'),
('Pencegahan Stunting', 'kesehatan', 'Program kesehatan ibu dan anak', 200, 150000000, 'active');
